### ISSUE TITLE
Exp wont share

### ISSUE THREAD

**Issue by redkk0523** [promcteam/proskillapiparties#3]
Exp wont shared i have the default settings for the plug but it doesnt work 

```
exp-modifications: 
  # Modifier for the number of members
  # normally ranging from 0 to 1
  # 0 -> Full experience for all members
  # 1 -> Evenly split experience
  members: '1'
  # Modifier for the difference in level
  # between party members
  # Generally should be small decimals
  # (0 - 0.01 is a good range)
  # 0 -> No change in experience
  level: '0'

```  
  heres a video for reference 
https://streamable.com/01jf00
